### ISSUE TITLE
Settings tab: Implement `gene.sampling.retrieve` under `1. Taxa`

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/phruta_app#1]
The two arguments in `1. Taxa` correspond to the ones in `gene.sampling.retrieve` from `phruta`. Please concatenate both strings (`clades` and `species`) and pass them to `gene.sampling.retrieve`.

**Comment by crownk12** [comment]
I tried a few time to concatenate both strings, but there are still some issues. (I think the reason of the issue is some based packages of phruta...)
How can I see your phruta codes?

**Comment by cromanpa94** [comment]
You can fine phruta in the following repo: https://github.com/cromanpa94/phruta. I’m happy to meet if you need additional clarification. Please don’t forget to usecheck out the vignettes as well!


--

Cristian Román-Palacios

Assistant Professor of Practice

School of Information

University of Arizona

Personal website: http://cromanpa94.github.io/cromanpa/

Official website: https://ischool.arizona.edu/people/cristian-roman-palacios

E-mail: ***@***.******@***.***>

Zoom link: https://arizona.zoom.us/my/cromanpa

Schedule a meeting: https://calendly.com/cromanpa/15min

Office: 520-621-5219

________________________________

**Comment by cromanpa94** [comment]
This update was part of https://github.com/cromanpa94/salphycon/commit/f075f96e70782f4ac484e5bba6d4c5a846899be4.
