### ISSUE TITLE
Settings: Make the drop down menu functional under `1. Taxa`

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/phruta_app#2]
Users can also select a file (one string per line and upload it). The dataset that users submit must be passed to ` gene.sampling.retrieve`.  Assume that the dataset have the following structure:

```
Felis
Vulpes
Phoca
Manis_pentadactyla
```

**Comment by crownk12** [comment]
Do you think which format is good for the dataset?
(e.g., txt file, csv file, etc....)

**Comment by cromanpa94** [comment]
A plain txt should be ok


--

Cristian Román-Palacios

Assistant Professor of Practice

School of Information

University of Arizona

Personal website: http://cromanpa94.github.io/cromanpa/

Official website: https://ischool.arizona.edu/people/cristian-roman-palacios

E-mail: ***@***.******@***.***>

Zoom link: https://arizona.zoom.us/my/cromanpa

Schedule a meeting: https://calendly.com/cromanpa/15min

Office: 520-621-5219

________________________________

**Comment by cromanpa94** [comment]
Feature implemented in: https://github.com/cromanpa94/salphycon/commit/f075f96e70782f4ac484e5bba6d4c5a846899be4. Template files also available from: https://github.com/cromanpa94/salphycon/commit/e0ad23d673d0b6a7070cd78af00758d58d7a61e9.
